// service/admin.ts — VPS 上让 dsh 管理页能「更新 / 卸载」（设计 §14.9）
//
// 守护进程以 dsh 用户运行，而更新（npm 全局目录、系统服务）和卸载（Caddy、防火墙、系统服务）要 root。
// 所以 setup（root）装一个 systemd path 单元：守护进程在 <home>/admin/request 写一张请求单，
// systemd 以 root 运行 `dsh-model admin-run`，它只认两件固定的事：更新到 npm 最新版、卸载。别的一律拒绝。

import { chown, mkdir, readFile, rm } from 'node:fs/promises'
import { join } from 'node:path'
import type { Ctx } from '../context.js'
import { run } from '../util/exec.js'
import { atomicWrite, exists } from '../util/fs.js'
import { PKG_ROOT } from '../util/pkg.js'

export const ADMIN_PATH_UNIT = '/etc/systemd/system/dsh-model-admin.path'
export const ADMIN_SERVICE_UNIT = '/etc/systemd/system/dsh-model-admin.service'

export interface AdminRequest {
  action: 'update' | 'uninstall'
  keepAuth?: boolean
  lang?: 'zh' | 'en'
}

export const adminDir = (ctx: Ctx) => join(ctx.paths.home, 'admin')
export const adminRequestPath = (ctx: Ctx) => join(adminDir(ctx), 'request')

export async function adminInstalled(): Promise<boolean> {
  return exists(ADMIN_PATH_UNIT)
}

/** setup / repair（root）时装上；幂等 */
export async function installAdmin(ctx: Ctx): Promise<void> {
  const dir = adminDir(ctx)
  await mkdir(dir, { recursive: true, mode: 0o700 })
  if (ctx.owner) await chown(dir, ctx.owner.uid, ctx.owner.gid)
  const path = [
    '# Generated by dsh-model. 由 dsh-model 生成：dsh 管理页的「更新 / 卸载」请求',
    '[Unit]',
    'Description=dsh-model admin requests from the dsh page',
    '',
    '[Path]',
    `PathExists=${adminRequestPath(ctx)}`,
    'Unit=dsh-model-admin.service',
    '',
    '[Install]',
    'WantedBy=multi-user.target',
    '',
  ].join('\n')
  const service = [
    '# Generated by dsh-model. 由 dsh-model 生成：以 root 执行管理页的请求（只认 update / uninstall）',
    '[Unit]',
    'Description=dsh-model admin (update / uninstall from the dsh page)',
    '',
    '[Service]',
    'Type=oneshot',
    `ExecStart=${process.execPath} ${join(PKG_ROOT, 'bin', 'dsh-model.js')} admin-run`,
    `Environment=DSH_MODEL_HOME=${ctx.paths.home}`,
    // 系统服务默认没有 HOME，npm 要用它放缓存
    'Environment=HOME=/root',
    '',
  ].join('\n')
  const before = (await readFile(ADMIN_PATH_UNIT, 'utf8').catch(() => '')) + (await readFile(ADMIN_SERVICE_UNIT, 'utf8').catch(() => ''))
  if (before === path + service) return
  await atomicWrite(ADMIN_PATH_UNIT, path, { mode: 0o644 })
  await atomicWrite(ADMIN_SERVICE_UNIT, service, { mode: 0o644 })
  await run('systemctl', ['daemon-reload'])
  await run('systemctl', ['enable', '--now', 'dsh-model-admin.path'])
}

export async function removeAdmin(): Promise<void> {
  if (!(await exists(ADMIN_PATH_UNIT)) && !(await exists(ADMIN_SERVICE_UNIT))) return
  await run('systemctl', ['disable', '--now', 'dsh-model-admin.path'])
  await rm(ADMIN_PATH_UNIT, { force: true })
  await rm(ADMIN_SERVICE_UNIT, { force: true })
  await run('systemctl', ['daemon-reload'])
}

/** 读并删掉请求单（先删，免得 path 单元反复触发）；不合规的返回 null */
export async function takeAdminRequest(ctx: Ctx): Promise<AdminRequest | null> {
  const file = adminRequestPath(ctx)
  let raw = ''
  try {
    raw = await readFile(file, 'utf8')
  } catch {
    return null
  }
  await rm(file, { force: true })
  try {
    const r = JSON.parse(raw) as Partial<AdminRequest>
    if (r.action !== 'update' && r.action !== 'uninstall') return null
    return { action: r.action, keepAuth: r.keepAuth === true, lang: r.lang === 'en' ? 'en' : 'zh' }
  } catch {
    return null
  }
}
