// service/launchd.ts — macOS 用户级 LaunchAgent（RunAtLoad + KeepAlive）

import { rm } from 'node:fs/promises'
import { DshModelError } from '../errors.js'
import { L } from '../i18n.js'
import { run } from '../util/exec.js'
import { atomicWrite, exists } from '../util/fs.js'
import type { ServiceManager, ServiceSpec, ServiceStatus } from './index.js'

const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

export function renderPlist(spec: ServiceSpec): string {
  const args = spec.program.map((a) => `    <string>${esc(a)}</string>`).join('\n')
  const envEntries = Object.entries(spec.env ?? {})
  const envBlock = envEntries.length
    ? `  <key>EnvironmentVariables</key>\n  <dict>\n${envEntries.map(([k, v]) => `    <key>${esc(k)}</key>\n    <string>${esc(v)}</string>`).join('\n')}\n  </dict>\n`
    : ''
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by dsh-model. 由 dsh-model 生成，卸载请执行 dsh-model uninstall -->
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${esc(spec.label)}</string>
  <key>ProgramArguments</key>
  <array>
${args}
  </array>
${envBlock}  <key>WorkingDirectory</key>
  <string>${esc(spec.workingDirectory)}</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ThrottleInterval</key>
  <integer>10</integer>
  <key>StandardOutPath</key>
  <string>${esc(spec.stdoutPath)}</string>
  <key>StandardErrorPath</key>
  <string>${esc(spec.stdoutPath)}</string>
</dict>
</plist>
`
}

export function launchd(spec: ServiceSpec): ServiceManager {
  const domain = `gui/${process.getuid?.() ?? 501}`
  const target = `${domain}/${spec.label}`

  const bootstrap = async () => {
    const r = await run('launchctl', ['bootstrap', domain, spec.file])
    // 已加载时返回 5 / 37（"service already loaded"），当成功
    if (r.code !== 0 && !/already|in progress|5:|37:/i.test(r.stderr)) {
      throw new DshModelError('service_failed', L(`launchctl bootstrap 失败：${r.stderr.trim()}`, `launchctl bootstrap failed: ${r.stderr.trim()}`))
    }
  }
  const bootout = async () => {
    await run('launchctl', ['bootout', target])
  }

  return {
    kind: 'launchd',
    spec,
    render: () => renderPlist(spec),
    async install() {
      await atomicWrite(spec.file, renderPlist(spec), { mode: 0o644 })
      await bootout()
      await bootstrap()
    },
    async start() {
      await bootstrap()
      await run('launchctl', ['kickstart', target])
    },
    async stop() {
      await bootout()
    },
    async restart() {
      const r = await run('launchctl', ['kickstart', '-k', target])
      if (r.code !== 0) await bootstrap()
    },
    async status(): Promise<ServiceStatus> {
      const installed = await exists(spec.file)
      const r = await run('launchctl', ['print', target])
      if (r.code !== 0) return { installed, running: false, detail: installed ? 'not loaded' : 'not installed' }
      const pid = Number(r.stdout.match(/\bpid = (\d+)/)?.[1]) || undefined
      const state = r.stdout.match(/\bstate = (\w+)/)?.[1]
      return { installed, running: state === 'running', pid, detail: state }
    },
    async uninstall() {
      await bootout()
      await rm(spec.file, { force: true })
    },
  }
}
