// service/systemd.ts — systemd 用户级（local/Linux）与系统级（vps，User=dsh）

import { rm } from 'node:fs/promises'
import { userInfo } from 'node:os'
import { DshModelError } from '../errors.js'
import { L } from '../i18n.js'
import { run } from '../util/exec.js'
import { atomicWrite, exists } from '../util/fs.js'
import { warn } from '../util/output.js'
import type { ServiceManager, ServiceSpec, ServiceStatus } from './index.js'

const quote = (a: string) => (/[\s"\\]/.test(a) ? `"${a.replace(/(["\\])/g, '\\$1')}"` : a)

export function renderUnit(spec: ServiceSpec, system: boolean): string {
  const lines = [
    '# Generated by dsh-model. 由 dsh-model 生成，卸载请执行 dsh-model uninstall',
    '[Unit]',
    'Description=dsh-model engine (CLIProxyAPI)',
    'After=network-online.target',
    'Wants=network-online.target',
    '',
    '[Service]',
    'Type=simple',
    `ExecStart=${spec.program.map(quote).join(' ')}`,
    `WorkingDirectory=${spec.workingDirectory}`,
    'Restart=on-failure',
    'RestartSec=5',
    `StandardOutput=append:${spec.stdoutPath}`,
    `StandardError=append:${spec.stdoutPath}`,
  ]
  if (system) {
    lines.push(
      `User=${spec.user}`,
      `Group=${spec.user}`,
      'NoNewPrivileges=yes',
      'PrivateTmp=yes',
      'ProtectSystem=strict',
      `ReadWritePaths=${spec.home}`,
    )
  }
  lines.push('', '[Install]', `WantedBy=${system ? 'multi-user.target' : 'default.target'}`, '')
  return lines.join('\n')
}

export function systemd(kind: 'systemd-user' | 'systemd-system', spec: ServiceSpec): ServiceManager {
  const system = kind === 'systemd-system'
  const sc = (...args: string[]) => run('systemctl', system ? args : ['--user', ...args])
  const must = async (...args: string[]) => {
    const r = await sc(...args)
    if (r.code !== 0) throw new DshModelError('service_failed', L(`systemctl ${args.join(' ')} 失败：${r.stderr.trim()}`, `systemctl ${args.join(' ')} failed: ${r.stderr.trim()}`))
  }

  return {
    kind,
    spec,
    render: () => renderUnit(spec, system),
    async install() {
      await atomicWrite(spec.file, renderUnit(spec, system), { mode: 0o644 })
      await must('daemon-reload')
      await must('enable', '--now', spec.label)
      if (!system) await checkLinger()
    },
    async start() {
      await must('start', spec.label)
    },
    async stop() {
      await sc('stop', spec.label)
    },
    async restart() {
      await must('restart', spec.label)
    },
    async status(): Promise<ServiceStatus> {
      const installed = await exists(spec.file)
      const r = await sc('show', spec.label, '-p', 'ActiveState', '-p', 'MainPID')
      const state = r.stdout.match(/ActiveState=(\w+)/)?.[1]
      const pid = Number(r.stdout.match(/MainPID=(\d+)/)?.[1]) || undefined
      return { installed, running: state === 'active', pid, detail: state }
    },
    async uninstall() {
      await sc('disable', '--now', spec.label)
      await rm(spec.file, { force: true })
      await sc('daemon-reload')
    },
  }
}

/** 用户级服务要开 linger 才能在退出登录后继续跑 */
async function checkLinger(): Promise<void> {
  const user = userInfo().username
  const r = await run('loginctl', ['show-user', user, '-p', 'Linger'])
  if (r.code === 0 && /Linger=no/.test(r.stdout)) {
    warn(
      L(
        `用户 ${user} 没开 linger：退出登录后引擎会停止。需要的话请执行 sudo loginctl enable-linger ${user}`,
        `Linger is off for ${user}: the engine stops when you log out. If needed run: sudo loginctl enable-linger ${user}`,
      ),
    )
  }
}
