// engine/config.ts — 由 config.json + keys.json 生成 engine.yaml（CLIProxyAPI v8 格式）
//
// 安全底线：api-keys 为空时引擎完全不鉴权（实测），所以没有可用 key 就拒绝生成。

import YAML from 'yaml'
import type { Ctx } from '../context.js'
import { DshModelError } from '../errors.js'
import { L } from '../i18n.js'
import { activeKeys, type KeyStore } from '../keys.js'
import type { Config } from '../state.js'
import { atomicWrite, readText } from '../util/fs.js'

const HEADER = [
  '# GENERATED BY dsh-model — DO NOT EDIT. Run `dsh-model setup` to regenerate.',
  '# 由 dsh-model 生成，请勿手改。需要重新生成请执行 `dsh-model setup`。',
].join('\n')

export function renderEngineConfig(ctx: Ctx, config: Config, keys: KeyStore, port = config.port): string {
  const apiKeys = activeKeys(keys).map((k) => k.key)
  if (apiKeys.length === 0) {
    throw new DshModelError('no_api_keys', L('没有可用的 key，拒绝生成引擎配置（空 key 列表会让引擎不做鉴权）', 'No active keys; refusing to write engine config (an empty key list disables engine auth)'))
  }
  const doc = {
    'config-version': 8,
    server: { host: '127.0.0.1', port },
    management: { 'allow-remote': false, 'secret-key': '', 'disable-control-panel': true },
    access: { 'api-keys': apiKeys },
    oauth: { 'auth-dir': ctx.paths.auth },
    routing: { strategy: 'fill-first' },
    ...(config.proxy ? { requests: { 'proxy-url': config.proxy } } : {}),
    observability: { logs: { 'logging-to-file': true, 'logs-max-total-size-mb': 50, 'request-log': false } },
  }
  return `${HEADER}\n${YAML.stringify(doc)}`
}

/** 写 engine.yaml；内容没变就不动（避免引擎无谓的热重载）。返回是否写了 */
export async function writeEngineConfig(ctx: Ctx, config: Config, keys: KeyStore): Promise<boolean> {
  const text = renderEngineConfig(ctx, config, keys)
  if ((await readText(ctx.paths.engineYaml)) === text) return false
  await atomicWrite(ctx.paths.engineYaml, text, { owner: ctx.owner })
  return true
}
